version: "3.8"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: phonebook_db
      MYSQL_USER: Sezgin
      MYSQL_PASSWORD: Sezgin_1
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - clarusnet
    configs:
      - source: initialdb
        target: /docker-entrypoint-initdb.d/init.sql

  app-server:
    image: "${ECR_REGISTRY}/${APP_REPO_NAME}:latest"
    deploy:
        mode: global
        update_config:
          parallelism: 2
          delay: 5s
          order: start-first
    ports:
      - "80:80"
    networks:
      - clarusnet

networks:
  clarusnet:
    driver: overlay

volumes:
    db-data:

configs:
  initialdb:
    file: ./init.sql

